spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: kafka:9092
#    bootstrap-servers: localhost:9092

    consumer:
      group-id: notify-group
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.demo.notification_service.Order
        spring.json.trusted.packages: "*"

server:
  port: 8081
