spring:
  application:
    name: order-service
  kafka:
    bootstrap-servers: kafka:9092
#    bootstrap-servers: localhost:9092

    properties:
      spring.json.add.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8080